### ISSUE TITLE
Data Check Speed

### ISSUE THREAD

**Issue by Huh** [annam21/spaceNtime#13]
For your reference and potentially a future enhancement:

```R
data checks: 768.72 sec elapsed
effort: 61.39 sec elapsed
calculate censors: 0.48 sec elapsed
calculate STE: 63.86 sec elapsed
```

Obviously the vast amount of time is spent in data checks, which may be a good thing, but I thought I would share in case you had some ideas about speeding things up.

**Comment by annam21** [comment]
I have sped this up considerably in version 1.1.1.
