### ISSUE TITLE
Add logical argument for printing information

### ISSUE THREAD

**Issue by Huh** [annam21/spaceNtime#16]
At the the moment the estimation function prints to the screen which can cause issues when creating markdown documents and the like. It would be nice to have something like print = T or msg = T or whatever

**Comment by Huh** [comment]
The messages come from ste_build_eh and are printed by tictoc

**Comment by annam21** [comment]
Added optional argument quiet = T in ste_build_eh, tte_build_eh, and ise_build_eh.
