### ISSUE TITLE
spaceNtime vignette - no vignettes found

### ISSUE THREAD

**Issue by scott-waller** [annam21/spaceNtime#17]
Hi there,

I'm trying to get started with your spaceNtime vignette (thanks for making one for all of us!). When I search for the spaceNtime vignette following your instructions, I get:

> browseVignettes( "spaceNtime" )
No vignettes found by browseVignettes("spaceNtime")

Others had the same problem when they tried. Is this a problem on my end or is there an issue with the vignette? 

Thanks!

Scott

**Comment by annam21** [comment]
It's an issue with the vignette. I thought it was fixed, but I will keep working on it!

**Comment by annam21** [comment]
It should work now if you use install_github(build_vignettes = TRUE)

**Comment by scott-waller** [comment]
Got it - thanks!
