### ISSUE TITLE
Q: camtoevent calculation question

### ISSUE THREAD

**Issue by Huh** [annam21/spaceNtime#4]
Asking because I will forget

On line 85 of ste_data_fn
```R
which(cc == cam)
```

The data prior to this step are subset to `event == i` and in the example this results in a single row, but I am wondering about multiple cameras taking a picture at the same event date-time.  A few examples where the cc set of values and cam are longer than one.  The first case is an error and should be, the other two...?
  
```R
> which(c(1, 2, 3) == 1:4)
[1] 1 2 3
Warning message:
In c(1, 2, 3) == 1:4 :
  longer object length is not a multiple of shorter object length
> which(1:2 == 1:2)
[1] 1 2
> which(2:1 == 1:2)
integer(0)
```

The function which is not quite vectorized in the way that I think it is being used, but I am not completely clear on the goal here either.  My guess is this... 
1) tab/cam_areas, in the example gives a lookup of cameras and areas
```R
> tab
# A tibble: 2 x 2
    cam     a
  <dbl> <dbl>
1     1   850
2     2  1100
```

2) randomize order of cameras using
```R
> cc <- sample(cam_areas$cam, length(cam_areas$cam), replace = F)
> cc
[1] 2 1
```

3) assign the position of the camera number in cc to camtoevent variable in data using
```R
dplyr::mutate(camtoevent = which(cc == cam))
```

I think this will only work if there is one camera per event...?  I illustrated this with the toy examples above and repeated here
```R
> which(1:2 == 1:2)
[1] 1 2
> which(2:1 == 1:2)
integer(0)
```

This is related to #3 and the meaning of event.  You certainly don't have to bring me along, but I was curious about what you were working on...if this is annoying just close it and move on.

**Comment by Huh** [comment]
I realized you use `rowwise` just prior to the line I referenced.  You might work around the rowwise with something like...

```R
#  Test data
df <- data.frame(
  event = rep(c(1:3), each = 2), 
  cam = rep(1:2, 3)
)

df %>% 
  group_by(event) %>% 
  mutate(
    c2e = sample(1:n(), n(), replace = F)
  )
```

However, #3 still matters and could make this comment irrelevant

**Comment by annam21** [comment]
Addressed in version 2.
