### ISSUE TITLE
suggested confidence interval change

### ISSUE THREAD

**Issue by paul-lukacs** [annam21/spaceNtime#5]
To avoid the risk of negative lower bound on CI's, it would be good to implement a log-normal CI

Example calculation:

    res <- ste_estN_fn(dat.ste)
    C <- exp( 1.96*sqrt(log(1+ (res$SE_N/res$estN)^2 )))
    UCL <- res$estN*C
   LCL <- res$estN/C

**Comment by annam21** [comment]
Changed in version2
