### ISSUE TITLE
ste_build_eh memory allocation

### ISSUE THREAD

**Issue by paul-lukacs** [annam21/spaceNtime#8]
> ste_eh <- ste_build_eh(w17t, deploy, occ)
Error: Evaluation error: cannot allocate vector of size 5.3 Gb.

Yikes - complete wolf data

**Comment by paul-lukacs** [comment]
This issue can be avoided by first filtering the data set to only include photos with wolves.

**Comment by annam21** [comment]
I filtered down to count >0 in the step that was failing. I think this should speed things up and still provide the same answers.
